### ISSUE TITLE
기본생성자(NoArgumentConstructor) 고려해보기

### ISSUE THREAD

**Issue by innoceive** [dalong417/dnflogs#3]
https://github.com/dalong417/dnflogs/blob/c5181f51ab955076a78b9b2874cc0ab6db0dc4d3/src/main/java/com/dalong/dnflogs/dnflogs/service/DNFOpenAPIService.java#L35

스프링 DI와 독립된다는 점과 객체모듈화 입장에서 @PostConstruct 도 괜찮지만 기본생성자를 따로 사용하지 않는 경우에는 해당 생성자에 init() 로직을 넣어도 좋음.
여기는 어차피 ApiComponent가 주입되기 때문에 생성자가 분기되기 때문에 해당 로직에 따라 판단하면 될것 같음!

**Comment by dionicis** [comment]
public DNFOpenAPIService(){
        this.init();
    }

    public void init() {
        mapper = new ObjectMapper();
        mapper.registerModule(new JavaTimeModule());
        headers = new HashMap<String, String>();
    }

이렇게 바뀌는겁니까?
